name: AM4 - Plane Depart

on:
  schedule:
    - cron: "*/5 * * * *"   # every 30 min
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Puppeteer deps
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Install npm packages
        run: npm install puppeteer

      - name: Run advanced tracker
        run: node testing.js
        env:
          LOGIN_URL: ${{ secrets.LOGIN_URL }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
